[supervisord]
nodaemon=true

[program:alarmCapture]
command=python /app/worksAlarm.py
autostart=true
autorestart=true

[program:fast_API]
command=python /app/main.py
autostart=true
autorestart=true

[program:streamlit]
command=streamlit run /app/advancePAY.py --server.port=8501
autostart=true
autorestart=true

[program:subF_hotLine]
command=python /app/subFunction/hotLineAuto.py
autostart=true
autorestart=true

[program:subF_ezMail]
command=python /app/subFunction/worksMail.py
autostart=true
autorestart=true